//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisMap.Data.dyvenpro
{
    using System;
    using System.Collections.Generic;
    
    public partial class BancosBarrio
    {
        public int id { get; set; }
        public string idbg { get; set; }
        public string tipo { get; set; }
        public string nombreLocal { get; set; }
        public string propietario { get; set; }
        public string direccion { get; set; }
        public string cedula { get; set; }
        public string tiponegocio { get; set; }
        public string provincia { get; set; }
        public string ciudad { get; set; }
        public string parroquia { get; set; }
        public string trmOfficia { get; set; }
        public string trmSupervi { get; set; }
        public string telefono { get; set; }
        public string codigomardis { get; set; }
        public Nullable<double> latitud { get; set; }
        public Nullable<double> longitud { get; set; }
        public string digitador { get; set; }
        public string imagen { get; set; }
        public Nullable<System.DateTime> fecha_Modificacion { get; set; }
        public string estado { get; set; }
    }
}
