//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisMap.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BG_DbsEntities : DbContext
    {
        public BG_DbsEntities()
            : base("name=BG_DbsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BancosBarrio> BancosBarrios { get; set; }
        public virtual DbSet<tb_bancos_descripcion> tb_bancos_descripcion { get; set; }
        public virtual DbSet<BancosBG> BancosBGs { get; set; }
    }
}
